### ISSUE TITLE
"Table header expected" errors everywhere

### ISSUE THREAD

**Issue by pkasarski** [AmailP/robot-plugin#24]
I have a TSV file, and every tab is marked as the above error. Example:
![table_error](https://cloud.githubusercontent.com/assets/1276286/12854261/40117118-cbfe-11e5-8183-016b07e73ac3.PNG)
![table_error2](https://cloud.githubusercontent.com/assets/1276286/12854290/7c05a478-cbfe-11e5-9dee-5da547f2dd33.PNG)
This test works, so I'm not sure why there are error markers.

**Comment by AmailP** [comment]
Hi @pkasarski,

the plugin supports only the ["Plain text format" specification](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#plain-text-format) for test cases and resources. In such format the table headers are mandatory.

Due to the amount of work needed and the many other aspects of RF that are not yet covered by the plugin, I personally do not have plans to support other file formats.

**Comment by pkasarski** [comment]
Ok, thank you for the explanation.
