### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by pavoltravnik** [AmailP/robot-plugin#33]
I am completly missing tutorial how to install this plugin in README.md file.

**Comment by pavoltravnik** [comment]
Installation for Mac. 
Download zip file
Click on IntelliJ IDEA -> Preferences - > Plugins - > Install Plugin from disk -> Select downloaded file - > OK ... Restart app if necessary

**Comment by AmailP** [comment]
Hi @pavoltravnik,

I was thinking that a specific tutorial was not required for this plugin, since the installation process is already covered [in the IDEA documentation](https://www.jetbrains.com/help/idea/2016.3/installing-updating-and-uninstalling-repository-plugins.html).

The procedure that you suggest works but is discouraged, since it does not allow automatic plugin update.
